### ISSUE TITLE
Flickering textures when imported into MMD

### ISSUE THREAD

**Issue by HadesandAzemCausingProblems** [wikid24/ffxiv_mmd_tools_helper#3] opened 2023-10-26 02:48 UTC
Tool works great and I am absolutely in love with it but some gear and clothing textures flicker when ported into MMD but looks and works fine in blender. Textures also do not flicker in PMX Editor. Unsure if this is a problem on my end or a issue with the plugin.
![texture flick 1](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/149030672/44343b1d-10ba-4ca4-b17c-b736f61644ce)
![texture flick 2](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/149030672/1aa87aa3-655d-4185-8494-905b351a3938)
![texture flick 3](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/149030672/f901fbc9-585d-4d88-805e-13783e33c8a5)

**Comment by wikid24** [comment] 2023-10-29 00:02
Hmm I am not sure, as I haven't been able to reproduce the issue on my end. PMX Editor is where I would go to investigate but  I usually only go so far as check to make sure that all of the MMD necessities are included in the FFXIV rig for export to PMX, 

Perhaps might want to ask the MMD Tools folks over on Discord? 

Best I can do is provide a link [MMD & Blender Discord Server](https://discord.gg/zRgUkuaPWw), and please let me know if you find a solution, I will add it to the FAQ!

**Comment by HadesandAzemCausingProblems** [comment] 2023-10-29 06:06
Hi! I went to the discord link you sent and someone mentioned the flickering issue had something to do with face overlapping and the fix is to separate or remove them, I tried removing by:

going into edit mode

pressing F3 

selecting the mesh with A

and typing in the search box, Mesh cleanup, merge by distance and selecting that. 

While this did solve the flickering issue, it sort of ruined the texture of the clothing, I even applied raycast over it to see if it would fix it somehow but that also didn't work.
![texture flick fixed but not really](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/149030672/c4125a99-4cba-41c0-8791-3e2aa33a8f7c)

**Comment by wikid24** [comment] 2023-10-31 05:30
oof ok yeah I'm not sure about the exact issue, but I do know that 'merge by distance' in blender usually never works the way I want it to when I use it for _other_ reasons, but since someone mentioned it is a face overlapping issue, perhaps it can be fixed by setting 'backface culling' in the materials panel to 'on' in blender before export to PMX? I don't know if that particular flag is exported to MMD Tools the file PMX export, but it's worth a shot

![image](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/19479648/d8d80e46-8453-4de9-bc40-1ebb5de2a60c)

**Comment by HadesandAzemCausingProblems** [comment] 2023-10-31 15:27
Hi, so the backface culling enabled didn't work no matter if it was turned on or off, what did work was simply joining the materials of the gear together...I could've sworn I tried that method before but guess not. I feel like a idiot lol.
![texture fixed](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/149030672/cf702b3c-5a86-4ec4-900a-417420f82e77)

**Comment by wikid24** [comment] 2023-11-01 17:58
nice, congrats on solving it! Yeah I usually avoid joining meshes in Blender as usually each mesh has different material properties and texture files associated with it, but I guess in this scenario it works fine :D

**Closed** 2023-11-05 02:47 UTC
